version: '3'
services:
  items-from-the-first-email-sql:
    container_name: items-from-the-first-email-sql
    image: 'mysql:8.0'
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_DATABASE=email_one


  items-from-the-first-email-app:
    container_name: items-from-the-first-email-app
    image: items-from-the-first-email:1.0
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-email-one:3306/email_one
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    links:
      - items-from-the-first-email-sql
    depends_on:
      - items-from-the-first-email-sql
    #command: mvn spring-boot:run
